export { default as Avatar } from "./avatar.vue";
export { default as CardAssessment } from "./card-assessment.vue";
export { default as CardReport } from "./card-report.vue";
export { default as CreateProposal } from "./create-proposal.vue";
export { default as Heading } from "./heading.vue";
export { default as Loading } from "./loading.vue";
export { default as Logo } from "./logo.vue";
export { default as Icon } from "./icons/icon.vue";
export { default as Panel } from "./panel.vue";
export { default as Toast } from "./toast.vue";
export { default as CardReportPlaceholder } from "./card-report-placeholder.vue";
export { default as ModalConnect } from "./modal-connect.vue";
export { default as ButtonExecute } from "./button-execute.vue";
export { default as PanelDepositButton } from "./panel-deposit-button.vue";

export { default as PanelDeposit } from "./panel-deposit.vue";
export { default as PanelWithdraw } from "./panel-withdraw.vue";
export { default as PanelReward } from "./panel-reward.vue";
export { default as ModalFaucet } from "./modal-faucet.vue";
